// AUTO-GENERATED by scripts/build-classic-data.mjs — DO NOT EDIT BY HAND
// Re-run with: pnpm --filter @geohunter/mini-demo run build:data
//
// Source: apps/web/public/data/rankings.csv (Classic mode rankings)

import type { Category, Country } from './types'

export const CLASSIC_CATEGORIES: Category[] = [
  { id: 'population',  name: 'Population',  icon: '👥' },
  { id: 'football',    name: 'Football',    icon: '⚽' },
  { id: 'small_size',  name: 'Small Size',  icon: '🏝️' },
  { id: 'crime_rate',  name: 'Crime Rate',  icon: '🚨' },
  { id: 'tourism',     name: 'Tourism',     icon: '🗺️' },
  { id: 'coffee',      name: 'Coffee',      icon: '☕' },
  { id: 'gdp',         name: 'GDP',         icon: '💰' },
  { id: 'natural_gas', name: 'Natural Gas', icon: '🔥' },
]

export const CLASSIC_COUNTRIES: Country[] = [
  {
    "name": "Afghanistan",
    "emoji": "🇦🇫",
    "rankings": {
      "crime_rate": 3,
      "population": 36,
      "natural_gas": 64
    }
  },
  {
    "name": "Albania",
    "emoji": "🇦🇱",
    "rankings": {
      "tourism": 32,
      "small_size": 56,
      "football": 64,
      "crime_rate": 90,
      "natural_gas": 92
    }
  },
  {
    "name": "Algeria",
    "emoji": "🇩🇿",
    "rankings": {
      "natural_gas": 11,
      "population": 32,
      "football": 37,
      "gdp": 49,
      "crime_rate": 58,
      "tourism": 83
    }
  },
  {
    "name": "Andorra",
    "emoji": "🇦🇩",
    "rankings": {
      "small_size": 17,
      "tourism": 56
    }
  },
  {
    "name": "Angola",
    "emoji": "🇦🇴",
    "rankings": {
      "crime_rate": 17,
      "coffee": 35,
      "natural_gas": 37,
      "population": 41,
      "gdp": 67,
      "tourism": 82,
      "football": 85
    }
  },
  {
    "name": "Antigua and Barbuda",
    "emoji": "🇦🇬",
    "rankings": {
      "small_size": 14
    }
  },
  {
    "name": "Argentina",
    "emoji": "🇦🇷",
    "rankings": {
      "football": 3,
      "crime_rate": 23,
      "gdp": 23,
      "population": 33,
      "natural_gas": 35,
      "tourism": 36
    }
  },
  {
    "name": "Armenia",
    "emoji": "🇦🇲",
    "rankings": {
      "small_size": 58,
      "football": 98
    }
  },
  {
    "name": "Australia",
    "emoji": "🇦🇺",
    "rankings": {
      "natural_gas": 13,
      "gdp": 14,
      "football": 25,
      "tourism": 39,
      "population": 54,
      "crime_rate": 80
    }
  },
  {
    "name": "Austria",
    "emoji": "🇦🇹",
    "rankings": {
      "tourism": 11,
      "football": 22,
      "gdp": 30,
      "small_size": 83,
      "natural_gas": 85,
      "population": 97
    }
  },
  {
    "name": "Azerbaijan",
    "emoji": "🇦🇿",
    "rankings": {
      "natural_gas": 17,
      "gdp": 82,
      "small_size": 84,
      "population": 93
    }
  },
  {
    "name": "Bahamas",
    "emoji": "🇧🇸",
    "rankings": {
      "small_size": 41,
      "crime_rate": 41,
      "tourism": 43
    }
  },
  {
    "name": "Bahrain",
    "emoji": "🇧🇭",
    "rankings": {
      "small_size": 23,
      "tourism": 47,
      "natural_gas": 58,
      "football": 84,
      "gdp": 92
    }
  },
  {
    "name": "Bangladesh",
    "emoji": "🇧🇩",
    "rankings": {
      "population": 8,
      "crime_rate": 28,
      "gdp": 35,
      "natural_gas": 52
    }
  },
  {
    "name": "Barbados",
    "emoji": "🇧🇧",
    "rankings": {
      "small_size": 13,
      "crime_rate": 81
    }
  },
  {
    "name": "Belarus",
    "emoji": "🇧🇾",
    "rankings": {
      "crime_rate": 66,
      "tourism": 73,
      "gdp": 84,
      "football": 95,
      "natural_gas": 95,
      "population": 98
    }
  },
  {
    "name": "Belgium",
    "emoji": "🇧🇪",
    "rankings": {
      "football": 8,
      "gdp": 22,
      "tourism": 34,
      "small_size": 60,
      "crime_rate": 71,
      "population": 81
    }
  },
  {
    "name": "Belize",
    "emoji": "🇧🇿",
    "rankings": {
      "small_size": 49,
      "crime_rate": 53,
      "coffee": 65,
      "tourism": 98
    }
  },
  {
    "name": "Benin",
    "emoji": "🇧🇯",
    "rankings": {
      "coffee": 66,
      "population": 77,
      "football": 88,
      "small_size": 96,
      "natural_gas": 99
    }
  },
  {
    "name": "Bhutan",
    "emoji": "🇧🇹",
    "rankings": {
      "small_size": 63
    }
  },
  {
    "name": "Bolivia",
    "emoji": "🇧🇴",
    "rankings": {
      "crime_rate": 22,
      "coffee": 30,
      "natural_gas": 40,
      "football": 74,
      "population": 84,
      "tourism": 86,
      "gdp": 87
    }
  },
  {
    "name": "Bosnia and Herzegovina",
    "emoji": "🇧🇦",
    "rankings": {
      "football": 70,
      "small_size": 71
    }
  },
  {
    "name": "Botswana",
    "emoji": "🇧🇼",
    "rankings": {
      "crime_rate": 61,
      "tourism": 95
    }
  },
  {
    "name": "Brazil",
    "emoji": "🇧🇷",
    "rankings": {
      "coffee": 1,
      "football": 6,
      "population": 7,
      "gdp": 10,
      "crime_rate": 20,
      "natural_gas": 36,
      "tourism": 42
    }
  },
  {
    "name": "Brunei",
    "emoji": "🇧🇳",
    "rankings": {
      "small_size": 32,
      "natural_gas": 42
    }
  },
  {
    "name": "Bulgaria",
    "emoji": "🇧🇬",
    "rankings": {
      "tourism": 37,
      "gdp": 66,
      "football": 82,
      "natural_gas": 88,
      "small_size": 93
    }
  },
  {
    "name": "Burkina Faso",
    "emoji": "🇧🇫",
    "rankings": {
      "crime_rate": 19,
      "population": 58,
      "football": 62
    }
  },
  {
    "name": "Burundi",
    "emoji": "🇧🇮",
    "rankings": {
      "coffee": 34,
      "small_size": 54,
      "population": 78
    }
  },
  {
    "name": "Cambodia",
    "emoji": "🇰🇭",
    "rankings": {
      "tourism": 48,
      "crime_rate": 54,
      "coffee": 58,
      "population": 71,
      "gdp": 91
    }
  },
  {
    "name": "Cameroon",
    "emoji": "🇨🇲",
    "rankings": {
      "crime_rate": 26,
      "coffee": 28,
      "football": 50,
      "natural_gas": 50,
      "population": 52,
      "gdp": 90
    }
  },
  {
    "name": "Canada",
    "emoji": "🇨🇦",
    "rankings": {
      "gdp": 9,
      "natural_gas": 16,
      "tourism": 20,
      "football": 26,
      "population": 37,
      "crime_rate": 92
    }
  },
  {
    "name": "Cape Verde",
    "emoji": "🇨🇻",
    "rankings": {
      "small_size": 30,
      "coffee": 67,
      "football": 68
    }
  },
  {
    "name": "Central African Republic",
    "emoji": "🇨🇫",
    "rankings": {
      "crime_rate": 10,
      "coffee": 10
    }
  },
  {
    "name": "Chad",
    "emoji": "🇹🇩",
    "rankings": {
      "crime_rate": 30,
      "population": 67
    }
  },
  {
    "name": "Chile",
    "emoji": "🇨🇱",
    "rankings": {
      "gdp": 44,
      "tourism": 53,
      "football": 55,
      "natural_gas": 55,
      "population": 63
    }
  },
  {
    "name": "China",
    "emoji": "🇨🇳",
    "rankings": {
      "population": 2,
      "gdp": 2,
      "tourism": 4,
      "natural_gas": 7,
      "coffee": 16,
      "football": 89
    }
  },
  {
    "name": "Colombia",
    "emoji": "🇨🇴",
    "rankings": {
      "coffee": 4,
      "football": 13,
      "population": 26,
      "crime_rate": 31,
      "gdp": 38,
      "tourism": 44,
      "natural_gas": 57
    }
  },
  {
    "name": "Comoros",
    "emoji": "🇰🇲",
    "rankings": {
      "small_size": 26,
      "coffee": 63,
      "football": 100
    }
  },
  {
    "name": "Costa Rica",
    "emoji": "🇨🇷",
    "rankings": {
      "coffee": 17,
      "football": 45,
      "crime_rate": 51,
      "small_size": 70,
      "gdp": 70,
      "tourism": 72
    }
  },
  {
    "name": "Croatia",
    "emoji": "🇭🇷",
    "rankings": {
      "football": 9,
      "tourism": 28,
      "gdp": 71,
      "small_size": 72,
      "natural_gas": 72
    }
  },
  {
    "name": "Cuba",
    "emoji": "🇨🇺",
    "rankings": {
      "coffee": 43,
      "natural_gas": 60,
      "population": 85,
      "tourism": 87,
      "small_size": 92
    }
  },
  {
    "name": "Cyprus",
    "emoji": "🇨🇾",
    "rankings": {
      "small_size": 34,
      "tourism": 55,
      "gdp": 98
    }
  },
  {
    "name": "Czech Republic",
    "emoji": "🇨🇿",
    "rankings": {
      "tourism": 31,
      "football": 38,
      "gdp": 41,
      "small_size": 81,
      "population": 86,
      "natural_gas": 94
    }
  },
  {
    "name": "Denmark",
    "emoji": "🇩🇰",
    "rankings": {
      "football": 20,
      "tourism": 23,
      "gdp": 36,
      "small_size": 66,
      "natural_gas": 70
    }
  },
  {
    "name": "Djibouti",
    "emoji": "🇩🇯",
    "rankings": {
      "small_size": 50,
      "crime_rate": 79
    }
  },
  {
    "name": "Dominica",
    "emoji": "🇩🇲",
    "rankings": {
      "small_size": 22,
      "coffee": 59
    }
  },
  {
    "name": "Dominican Republic",
    "emoji": "🇩🇴",
    "rankings": {
      "coffee": 31,
      "crime_rate": 33,
      "tourism": 40,
      "gdp": 62,
      "small_size": 68,
      "population": 87
    }
  },
  {
    "name": "DR Congo",
    "emoji": "🇨🇩",
    "rankings": {
      "population": 14,
      "crime_rate": 14,
      "coffee": 20,
      "football": 58,
      "gdp": 81,
      "natural_gas": 100
    }
  },
  {
    "name": "Ecuador",
    "emoji": "🇪🇨",
    "rankings": {
      "football": 24,
      "crime_rate": 27,
      "coffee": 41,
      "gdp": 63,
      "population": 72,
      "tourism": 75,
      "natural_gas": 80
    }
  },
  {
    "name": "Egypt",
    "emoji": "🇪🇬",
    "rankings": {
      "population": 15,
      "natural_gas": 19,
      "tourism": 22,
      "football": 34,
      "gdp": 43,
      "crime_rate": 77
    }
  },
  {
    "name": "El Salvador",
    "emoji": "🇸🇻",
    "rankings": {
      "coffee": 27,
      "crime_rate": 29,
      "small_size": 47,
      "football": 86
    }
  },
  {
    "name": "Equatorial Guinea",
    "emoji": "🇬🇶",
    "rankings": {
      "coffee": 46,
      "natural_gas": 49,
      "small_size": 55,
      "football": 90
    }
  },
  {
    "name": "Eritrea",
    "emoji": "🇪🇷",
    "rankings": {
      "small_size": 97
    }
  },
  {
    "name": "Estonia",
    "emoji": "🇪🇪",
    "rankings": {
      "small_size": 67,
      "gdp": 97
    }
  },
  {
    "name": "Eswatini",
    "emoji": "🇸🇿",
    "rankings": {
      "small_size": 43
    }
  },
  {
    "name": "Ethiopia",
    "emoji": "🇪🇹",
    "rankings": {
      "coffee": 5,
      "population": 13,
      "crime_rate": 65,
      "gdp": 65,
      "natural_gas": 73,
      "tourism": 97
    }
  },
  {
    "name": "Fiji",
    "emoji": "🇫🇯",
    "rankings": {
      "crime_rate": 40,
      "small_size": 45,
      "coffee": 70
    }
  },
  {
    "name": "Finland",
    "emoji": "🇫🇮",
    "rankings": {
      "gdp": 46,
      "tourism": 63,
      "football": 69
    }
  },
  {
    "name": "France",
    "emoji": "🇫🇷",
    "rankings": {
      "tourism": 1,
      "football": 2,
      "gdp": 7,
      "population": 20,
      "crime_rate": 44,
      "natural_gas": 84
    }
  },
  {
    "name": "Gabon",
    "emoji": "🇬🇦",
    "rankings": {
      "crime_rate": 56,
      "coffee": 64,
      "natural_gas": 71,
      "football": 76
    }
  },
  {
    "name": "Gambia",
    "emoji": "🇬🇲",
    "rankings": {
      "small_size": 37
    }
  },
  {
    "name": "Georgia",
    "emoji": "🇬🇪",
    "rankings": {
      "tourism": 50,
      "football": 66,
      "small_size": 77,
      "natural_gas": 82
    }
  },
  {
    "name": "Germany",
    "emoji": "🇩🇪",
    "rankings": {
      "gdp": 3,
      "tourism": 9,
      "football": 12,
      "population": 19,
      "natural_gas": 74
    }
  },
  {
    "name": "Ghana",
    "emoji": "🇬🇭",
    "rankings": {
      "population": 45,
      "coffee": 53,
      "football": 72,
      "natural_gas": 75,
      "gdp": 78,
      "crime_rate": 98
    }
  },
  {
    "name": "Greece",
    "emoji": "🇬🇷",
    "rankings": {
      "tourism": 10,
      "football": 39,
      "gdp": 50,
      "crime_rate": 83,
      "population": 91
    }
  },
  {
    "name": "Grenada",
    "emoji": "🇬🇩",
    "rankings": {
      "small_size": 11
    }
  },
  {
    "name": "Guatemala",
    "emoji": "🇬🇹",
    "rankings": {
      "coffee": 12,
      "gdp": 64,
      "population": 70,
      "small_size": 91,
      "football": 93
    }
  },
  {
    "name": "Guinea",
    "emoji": "🇬🇳",
    "rankings": {
      "coffee": 11,
      "crime_rate": 55,
      "population": 75,
      "football": 78
    }
  },
  {
    "name": "Guinea-Bissau",
    "emoji": "🇬🇼",
    "rankings": {
      "small_size": 62,
      "crime_rate": 62
    }
  },
  {
    "name": "Guyana",
    "emoji": "🇬🇾",
    "rankings": {
      "crime_rate": 16,
      "natural_gas": 34,
      "coffee": 57
    }
  },
  {
    "name": "Haiti",
    "emoji": "🇭🇹",
    "rankings": {
      "crime_rate": 4,
      "coffee": 44,
      "small_size": 53,
      "population": 80,
      "football": 83
    }
  },
  {
    "name": "Honduras",
    "emoji": "🇭🇳",
    "rankings": {
      "crime_rate": 6,
      "coffee": 9,
      "football": 63,
      "population": 95,
      "small_size": 95,
      "gdp": 100
    }
  },
  {
    "name": "Hungary",
    "emoji": "🇭🇺",
    "rankings": {
      "tourism": 25,
      "football": 40,
      "gdp": 53,
      "small_size": 88,
      "population": 96,
      "natural_gas": 96
    }
  },
  {
    "name": "Iceland",
    "emoji": "🇮🇸",
    "rankings": {
      "tourism": 70,
      "football": 71,
      "small_size": 90
    }
  },
  {
    "name": "India",
    "emoji": "🇮🇳",
    "rankings": {
      "population": 1,
      "gdp": 4,
      "coffee": 8,
      "natural_gas": 23,
      "crime_rate": 96
    }
  },
  {
    "name": "Indonesia",
    "emoji": "🇮🇩",
    "rankings": {
      "coffee": 3,
      "population": 4,
      "gdp": 17,
      "natural_gas": 26,
      "tourism": 29,
      "crime_rate": 88
    }
  },
  {
    "name": "Iran",
    "emoji": "🇮🇷",
    "rankings": {
      "natural_gas": 2,
      "population": 17,
      "football": 21,
      "gdp": 37,
      "tourism": 46,
      "crime_rate": 69
    }
  },
  {
    "name": "Iraq",
    "emoji": "🇮🇶",
    "rankings": {
      "natural_gas": 12,
      "population": 35,
      "gdp": 51,
      "football": 56,
      "tourism": 84,
      "crime_rate": 94
    }
  },
  {
    "name": "Ireland",
    "emoji": "🇮🇪",
    "rankings": {
      "gdp": 25,
      "tourism": 41,
      "football": 59,
      "small_size": 78,
      "natural_gas": 81,
      "crime_rate": 85
    }
  },
  {
    "name": "Israel",
    "emoji": "🇮🇱",
    "rankings": {
      "gdp": 26,
      "natural_gas": 47,
      "small_size": 48,
      "football": 73,
      "population": 94
    }
  },
  {
    "name": "Italy",
    "emoji": "🇮🇹",
    "rankings": {
      "tourism": 5,
      "gdp": 8,
      "football": 10,
      "population": 25,
      "natural_gas": 66,
      "crime_rate": 78
    }
  },
  {
    "name": "Ivory Coast",
    "emoji": "🇨🇮",
    "rankings": {
      "coffee": 18,
      "crime_rate": 38,
      "football": 42,
      "population": 50,
      "natural_gas": 68,
      "gdp": 73
    }
  },
  {
    "name": "Jamaica",
    "emoji": "🇯🇲",
    "rankings": {
      "crime_rate": 13,
      "small_size": 36,
      "coffee": 40,
      "football": 67,
      "tourism": 67
    }
  },
  {
    "name": "Japan",
    "emoji": "🇯🇵",
    "rankings": {
      "gdp": 5,
      "population": 11,
      "tourism": 16,
      "football": 19,
      "natural_gas": 76
    }
  },
  {
    "name": "Jordan",
    "emoji": "🇯🇴",
    "rankings": {
      "tourism": 49,
      "football": 60,
      "population": 83,
      "small_size": 86,
      "natural_gas": 87,
      "gdp": 89
    }
  },
  {
    "name": "Kazakhstan",
    "emoji": "🇰🇿",
    "rankings": {
      "natural_gas": 15,
      "gdp": 48,
      "tourism": 54,
      "population": 61,
      "crime_rate": 89
    }
  },
  {
    "name": "Kenya",
    "emoji": "🇰🇪",
    "rankings": {
      "coffee": 23,
      "population": 27,
      "crime_rate": 42,
      "gdp": 61,
      "tourism": 77
    }
  },
  {
    "name": "Kiribati",
    "emoji": "🇰🇮",
    "rankings": {
      "small_size": 24
    }
  },
  {
    "name": "Kuwait",
    "emoji": "🇰🇼",
    "rankings": {
      "natural_gas": 20,
      "small_size": 44,
      "gdp": 58
    }
  },
  {
    "name": "Kyrgyzstan",
    "emoji": "🇰🇬",
    "rankings": {
      "crime_rate": 49,
      "natural_gas": 91
    }
  },
  {
    "name": "Laos",
    "emoji": "🇱🇦",
    "rankings": {
      "coffee": 14,
      "tourism": 89
    }
  },
  {
    "name": "Latvia",
    "emoji": "🇱🇻",
    "rankings": {
      "small_size": 74,
      "gdp": 95
    }
  },
  {
    "name": "Lebanon",
    "emoji": "🇱🇧",
    "rankings": {
      "small_size": 35,
      "crime_rate": 87
    }
  },
  {
    "name": "Lesotho",
    "emoji": "🇱🇸",
    "rankings": {
      "crime_rate": 11,
      "small_size": 59
    }
  },
  {
    "name": "Liberia",
    "emoji": "🇱🇷",
    "rankings": {
      "crime_rate": 52,
      "coffee": 56,
      "small_size": 94
    }
  },
  {
    "name": "Libya",
    "emoji": "🇱🇾",
    "rankings": {
      "natural_gas": 22,
      "crime_rate": 34,
      "gdp": 93
    }
  },
  {
    "name": "Liechtenstein",
    "emoji": "🇱🇮",
    "rankings": {
      "small_size": 6
    }
  },
  {
    "name": "Lithuania",
    "emoji": "🇱🇹",
    "rankings": {
      "small_size": 75,
      "gdp": 76
    }
  },
  {
    "name": "Luxembourg",
    "emoji": "🇱🇺",
    "rankings": {
      "small_size": 28,
      "tourism": 68,
      "gdp": 72,
      "football": 91
    }
  },
  {
    "name": "Madagascar",
    "emoji": "🇲🇬",
    "rankings": {
      "coffee": 24,
      "crime_rate": 39,
      "population": 49
    }
  },
  {
    "name": "Malawi",
    "emoji": "🇲🇼",
    "rankings": {
      "coffee": 37,
      "population": 62,
      "small_size": 98
    }
  },
  {
    "name": "Malaysia",
    "emoji": "🇲🇾",
    "rankings": {
      "tourism": 18,
      "natural_gas": 24,
      "gdp": 34,
      "population": 42,
      "coffee": 47,
      "crime_rate": 67
    }
  },
  {
    "name": "Maldives",
    "emoji": "🇲🇻",
    "rankings": {
      "small_size": 9,
      "crime_rate": 46,
      "tourism": 94
    }
  },
  {
    "name": "Mali",
    "emoji": "🇲🇱",
    "rankings": {
      "crime_rate": 35,
      "football": 54,
      "population": 59
    }
  },
  {
    "name": "Malta",
    "emoji": "🇲🇹",
    "rankings": {
      "small_size": 10,
      "tourism": 69
    }
  },
  {
    "name": "Marshall Islands",
    "emoji": "🇲🇭",
    "rankings": {
      "small_size": 7
    }
  },
  {
    "name": "Mauritania",
    "emoji": "🇲🇷",
    "rankings": {
      "natural_gas": 69
    }
  },
  {
    "name": "Mauritius",
    "emoji": "🇲🇺",
    "rankings": {
      "small_size": 27,
      "crime_rate": 74
    }
  },
  {
    "name": "Mexico",
    "emoji": "🇲🇽",
    "rankings": {
      "tourism": 7,
      "population": 10,
      "coffee": 13,
      "football": 14,
      "gdp": 15,
      "natural_gas": 45,
      "crime_rate": 50
    }
  },
  {
    "name": "Micronesia",
    "emoji": "🇫🇲",
    "rankings": {
      "small_size": 19
    }
  },
  {
    "name": "Moldova",
    "emoji": "🇲🇩",
    "rankings": {
      "small_size": 61,
      "natural_gas": 77,
      "crime_rate": 93
    }
  },
  {
    "name": "Monaco",
    "emoji": "🇲🇨",
    "rankings": {
      "small_size": 2
    }
  },
  {
    "name": "Mongolia",
    "emoji": "🇲🇳",
    "rankings": {
      "crime_rate": 57
    }
  },
  {
    "name": "Montenegro",
    "emoji": "🇲🇪",
    "rankings": {
      "small_size": 40,
      "football": 77,
      "tourism": 93
    }
  },
  {
    "name": "Morocco",
    "emoji": "🇲🇦",
    "rankings": {
      "football": 11,
      "tourism": 24,
      "population": 40,
      "gdp": 57,
      "crime_rate": 84,
      "natural_gas": 98
    }
  },
  {
    "name": "Mozambique",
    "emoji": "🇲🇿",
    "rankings": {
      "natural_gas": 14,
      "crime_rate": 25,
      "population": 44,
      "coffee": 52,
      "football": 92,
      "tourism": 100
    }
  },
  {
    "name": "Myanmar",
    "emoji": "🇲🇲",
    "rankings": {
      "population": 28,
      "natural_gas": 31,
      "coffee": 38,
      "crime_rate": 68,
      "tourism": 78,
      "gdp": 85
    }
  },
  {
    "name": "Namibia",
    "emoji": "🇳🇦",
    "rankings": {
      "crime_rate": 24,
      "natural_gas": 62
    }
  },
  {
    "name": "Nauru",
    "emoji": "🇳🇷",
    "rankings": {
      "small_size": 3
    }
  },
  {
    "name": "Nepal",
    "emoji": "🇳🇵",
    "rankings": {
      "population": 51,
      "tourism": 59,
      "coffee": 60,
      "gdp": 94
    }
  },
  {
    "name": "Netherlands",
    "emoji": "🇳🇱",
    "rankings": {
      "football": 7,
      "tourism": 17,
      "gdp": 18,
      "natural_gas": 51,
      "small_size": 65,
      "population": 69
    }
  },
  {
    "name": "New Zealand",
    "emoji": "🇳🇿",
    "rankings": {
      "gdp": 52,
      "tourism": 60,
      "natural_gas": 67,
      "crime_rate": 75,
      "football": 80
    }
  },
  {
    "name": "Nicaragua",
    "emoji": "🇳🇮",
    "rankings": {
      "coffee": 15,
      "crime_rate": 59,
      "tourism": 88,
      "small_size": 100
    }
  },
  {
    "name": "Niger",
    "emoji": "🇳🇪",
    "rankings": {
      "crime_rate": 43,
      "population": 55
    }
  },
  {
    "name": "Nigeria",
    "emoji": "🇳🇬",
    "rankings": {
      "population": 6,
      "natural_gas": 10,
      "crime_rate": 18,
      "football": 43,
      "coffee": 51,
      "gdp": 56,
      "tourism": 80
    }
  },
  {
    "name": "North Korea",
    "emoji": "🇰🇵",
    "rankings": {
      "population": 56,
      "crime_rate": 63,
      "small_size": 99
    }
  },
  {
    "name": "North Macedonia",
    "emoji": "🇲🇰",
    "rankings": {
      "small_size": 51,
      "football": 61
    }
  },
  {
    "name": "Norway",
    "emoji": "🇳🇴",
    "rankings": {
      "natural_gas": 21,
      "football": 30,
      "gdp": 31,
      "tourism": 62
    }
  },
  {
    "name": "Oman",
    "emoji": "🇴🇲",
    "rankings": {
      "natural_gas": 30,
      "gdp": 69,
      "football": 75
    }
  },
  {
    "name": "Pakistan",
    "emoji": "🇵🇰",
    "rankings": {
      "population": 5,
      "natural_gas": 32,
      "gdp": 42,
      "tourism": 79,
      "crime_rate": 99
    }
  },
  {
    "name": "Palau",
    "emoji": "🇵🇼",
    "rankings": {
      "small_size": 16
    }
  },
  {
    "name": "Palestine",
    "emoji": "🇵🇸",
    "rankings": {
      "small_size": 33,
      "football": 94
    }
  },
  {
    "name": "Panama",
    "emoji": "🇵🇦",
    "rankings": {
      "football": 29,
      "coffee": 42,
      "tourism": 71,
      "gdp": 75,
      "small_size": 80,
      "crime_rate": 97
    }
  },
  {
    "name": "Papua New Guinea",
    "emoji": "🇵🇬",
    "rankings": {
      "crime_rate": 2,
      "coffee": 25,
      "natural_gas": 44,
      "population": 82
    }
  },
  {
    "name": "Paraguay",
    "emoji": "🇵🇾",
    "rankings": {
      "football": 36,
      "coffee": 61,
      "crime_rate": 64,
      "tourism": 92,
      "gdp": 96
    }
  },
  {
    "name": "Peru",
    "emoji": "🇵🇪",
    "rankings": {
      "coffee": 7,
      "crime_rate": 15,
      "natural_gas": 38,
      "population": 43,
      "football": 46,
      "gdp": 47,
      "tourism": 64
    }
  },
  {
    "name": "Philippines",
    "emoji": "🇵🇭",
    "rankings": {
      "population": 12,
      "coffee": 21,
      "gdp": 32,
      "tourism": 35,
      "natural_gas": 54,
      "crime_rate": 100
    }
  },
  {
    "name": "Poland",
    "emoji": "🇵🇱",
    "rankings": {
      "tourism": 19,
      "gdp": 20,
      "football": 35,
      "population": 39,
      "natural_gas": 56
    }
  },
  {
    "name": "Portugal",
    "emoji": "🇵🇹",
    "rankings": {
      "football": 5,
      "tourism": 15,
      "gdp": 45,
      "small_size": 87,
      "population": 89
    }
  },
  {
    "name": "Qatar",
    "emoji": "🇶🇦",
    "rankings": {
      "natural_gas": 3,
      "small_size": 38,
      "football": 51,
      "tourism": 51,
      "gdp": 54
    }
  },
  {
    "name": "Republic of the Congo",
    "emoji": "🇨🇬",
    "rankings": {
      "natural_gas": 41,
      "crime_rate": 48,
      "coffee": 48
    }
  },
  {
    "name": "Romania",
    "emoji": "🇷🇴",
    "rankings": {
      "gdp": 40,
      "football": 49,
      "natural_gas": 53,
      "population": 65,
      "tourism": 65
    }
  },
  {
    "name": "Russia",
    "emoji": "🇷🇺",
    "rankings": {
      "natural_gas": 1,
      "population": 9,
      "gdp": 11,
      "football": 32,
      "tourism": 61
    }
  },
  {
    "name": "Rwanda",
    "emoji": "🇷🇼",
    "rankings": {
      "coffee": 32,
      "small_size": 52,
      "natural_gas": 63,
      "population": 76,
      "tourism": 90
    }
  },
  {
    "name": "Saint Kitts and Nevis",
    "emoji": "🇰🇳",
    "rankings": {
      "small_size": 8
    }
  },
  {
    "name": "Saint Lucia",
    "emoji": "🇱🇨",
    "rankings": {
      "small_size": 18
    }
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "emoji": "🇻🇨",
    "rankings": {
      "small_size": 12,
      "coffee": 62
    }
  },
  {
    "name": "Samoa",
    "emoji": "🇼🇸",
    "rankings": {
      "small_size": 29,
      "coffee": 71
    }
  },
  {
    "name": "San Marino",
    "emoji": "🇸🇲",
    "rankings": {
      "small_size": 5
    }
  },
  {
    "name": "Sao Tome and Principe",
    "emoji": "🇸🇹",
    "rankings": {
      "small_size": 25,
      "crime_rate": 37,
      "coffee": 72
    }
  },
  {
    "name": "Saudi Arabia",
    "emoji": "🇸🇦",
    "rankings": {
      "natural_gas": 6,
      "tourism": 14,
      "gdp": 19,
      "population": 48,
      "football": 57
    }
  },
  {
    "name": "Senegal",
    "emoji": "🇸🇳",
    "rankings": {
      "football": 18,
      "natural_gas": 27,
      "population": 68,
      "tourism": 99
    }
  },
  {
    "name": "Serbia",
    "emoji": "🇷🇸",
    "rankings": {
      "football": 33,
      "tourism": 57,
      "natural_gas": 65,
      "gdp": 74,
      "small_size": 85
    }
  },
  {
    "name": "Seychelles",
    "emoji": "🇸🇨",
    "rankings": {
      "small_size": 15
    }
  },
  {
    "name": "Sierra Leone",
    "emoji": "🇸🇱",
    "rankings": {
      "crime_rate": 36,
      "coffee": 49,
      "small_size": 79,
      "population": 100
    }
  },
  {
    "name": "Singapore",
    "emoji": "🇸🇬",
    "rankings": {
      "small_size": 20,
      "gdp": 27,
      "tourism": 30
    }
  },
  {
    "name": "Slovakia",
    "emoji": "🇸🇰",
    "rankings": {
      "football": 41,
      "gdp": 59,
      "tourism": 66,
      "small_size": 69,
      "natural_gas": 78
    }
  },
  {
    "name": "Slovenia",
    "emoji": "🇸🇮",
    "rankings": {
      "small_size": 46,
      "football": 48,
      "gdp": 83
    }
  },
  {
    "name": "Solomon Islands",
    "emoji": "🇸🇧",
    "rankings": {
      "small_size": 57
    }
  },
  {
    "name": "Somalia",
    "emoji": "🇸🇴",
    "rankings": {
      "crime_rate": 21,
      "population": 66,
      "natural_gas": 89
    }
  },
  {
    "name": "South Africa",
    "emoji": "🇿🇦",
    "rankings": {
      "crime_rate": 5,
      "population": 23,
      "tourism": 38,
      "gdp": 39,
      "football": 53,
      "natural_gas": 93
    }
  },
  {
    "name": "South Korea",
    "emoji": "🇰🇷",
    "rankings": {
      "gdp": 13,
      "football": 23,
      "tourism": 27,
      "population": 29,
      "natural_gas": 83,
      "small_size": 89
    }
  },
  {
    "name": "South Sudan",
    "emoji": "🇸🇸",
    "rankings": {
      "crime_rate": 7,
      "population": 74
    }
  },
  {
    "name": "Spain",
    "emoji": "🇪🇸",
    "rankings": {
      "football": 1,
      "tourism": 2,
      "gdp": 12,
      "population": 31,
      "natural_gas": 97
    }
  },
  {
    "name": "Sri Lanka",
    "emoji": "🇱🇰",
    "rankings": {
      "coffee": 45,
      "tourism": 58,
      "population": 60,
      "small_size": 76
    }
  },
  {
    "name": "Sudan",
    "emoji": "🇸🇩",
    "rankings": {
      "population": 30,
      "natural_gas": 59,
      "crime_rate": 91
    }
  },
  {
    "name": "Suriname",
    "emoji": "🇸🇷",
    "rankings": {
      "coffee": 73
    }
  },
  {
    "name": "Sweden",
    "emoji": "🇸🇪",
    "rankings": {
      "gdp": 24,
      "football": 31,
      "tourism": 45,
      "crime_rate": 73,
      "population": 90
    }
  },
  {
    "name": "Switzerland",
    "emoji": "🇨🇭",
    "rankings": {
      "football": 17,
      "tourism": 21,
      "gdp": 21,
      "small_size": 64,
      "population": 99
    }
  },
  {
    "name": "Syria",
    "emoji": "🇸🇾",
    "rankings": {
      "crime_rate": 9,
      "natural_gas": 43,
      "population": 57,
      "tourism": 85,
      "football": 87
    }
  },
  {
    "name": "Tajikistan",
    "emoji": "🇹🇯",
    "rankings": {
      "natural_gas": 90,
      "population": 92,
      "football": 99
    }
  },
  {
    "name": "Tanzania",
    "emoji": "🇹🇿",
    "rankings": {
      "coffee": 19,
      "population": 24,
      "crime_rate": 47,
      "tourism": 76,
      "gdp": 79,
      "natural_gas": 86
    }
  },
  {
    "name": "Thailand",
    "emoji": "🇹🇭",
    "rankings": {
      "tourism": 12,
      "population": 22,
      "gdp": 29,
      "coffee": 33,
      "natural_gas": 48,
      "football": 96
    }
  },
  {
    "name": "Timor-Leste",
    "emoji": "🇹🇱",
    "rankings": {
      "coffee": 36,
      "small_size": 42
    }
  },
  {
    "name": "Togo",
    "emoji": "🇹🇬",
    "rankings": {
      "coffee": 29,
      "crime_rate": 72,
      "small_size": 73
    }
  },
  {
    "name": "Tonga",
    "emoji": "🇹🇴",
    "rankings": {
      "small_size": 21,
      "coffee": 69
    }
  },
  {
    "name": "Trinidad and Tobago",
    "emoji": "🇹🇹",
    "rankings": {
      "crime_rate": 8,
      "small_size": 31,
      "natural_gas": 39,
      "coffee": 54,
      "football": 97
    }
  },
  {
    "name": "Tunisia",
    "emoji": "🇹🇳",
    "rankings": {
      "tourism": 33,
      "football": 44,
      "natural_gas": 61,
      "population": 79,
      "gdp": 88,
      "crime_rate": 95
    }
  },
  {
    "name": "Turkey",
    "emoji": "🇹🇷",
    "rankings": {
      "tourism": 6,
      "gdp": 16,
      "population": 18,
      "football": 27,
      "natural_gas": 28
    }
  },
  {
    "name": "Turkmenistan",
    "emoji": "🇹🇲",
    "rankings": {
      "natural_gas": 5,
      "gdp": 77
    }
  },
  {
    "name": "Tuvalu",
    "emoji": "🇹🇻",
    "rankings": {
      "small_size": 4
    }
  },
  {
    "name": "Uganda",
    "emoji": "🇺🇬",
    "rankings": {
      "coffee": 6,
      "population": 34,
      "crime_rate": 45,
      "football": 79,
      "natural_gas": 79,
      "tourism": 81,
      "gdp": 86
    }
  },
  {
    "name": "Ukraine",
    "emoji": "🇺🇦",
    "rankings": {
      "natural_gas": 25,
      "football": 28,
      "population": 46,
      "gdp": 55,
      "tourism": 74,
      "crime_rate": 82
    }
  },
  {
    "name": "United Arab Emirates",
    "emoji": "🇦🇪",
    "rankings": {
      "natural_gas": 8,
      "tourism": 13,
      "gdp": 28,
      "football": 65,
      "small_size": 82,
      "population": 88
    }
  },
  {
    "name": "United Kingdom",
    "emoji": "🇬🇧",
    "rankings": {
      "football": 4,
      "gdp": 6,
      "tourism": 8,
      "population": 21,
      "natural_gas": 46,
      "crime_rate": 76
    }
  },
  {
    "name": "United States",
    "emoji": "🇺🇸",
    "rankings": {
      "gdp": 1,
      "population": 3,
      "tourism": 3,
      "natural_gas": 4,
      "football": 16,
      "coffee": 50,
      "crime_rate": 70
    }
  },
  {
    "name": "Uruguay",
    "emoji": "🇺🇾",
    "rankings": {
      "football": 15,
      "tourism": 52,
      "crime_rate": 60,
      "gdp": 80
    }
  },
  {
    "name": "Uzbekistan",
    "emoji": "🇺🇿",
    "rankings": {
      "natural_gas": 18,
      "population": 38,
      "football": 52,
      "gdp": 60
    }
  },
  {
    "name": "Vanuatu",
    "emoji": "🇻🇺",
    "rankings": {
      "small_size": 39,
      "coffee": 68
    }
  },
  {
    "name": "Vatican City",
    "emoji": "🇻🇦",
    "rankings": {
      "small_size": 1
    }
  },
  {
    "name": "Venezuela",
    "emoji": "🇻🇪",
    "rankings": {
      "crime_rate": 1,
      "natural_gas": 9,
      "coffee": 22,
      "football": 47,
      "population": 53,
      "gdp": 68
    }
  },
  {
    "name": "Vietnam",
    "emoji": "🇻🇳",
    "rankings": {
      "coffee": 2,
      "population": 16,
      "tourism": 26,
      "natural_gas": 29,
      "gdp": 33
    }
  },
  {
    "name": "Yemen",
    "emoji": "🇾🇪",
    "rankings": {
      "crime_rate": 12,
      "coffee": 26,
      "natural_gas": 33,
      "population": 47
    }
  },
  {
    "name": "Zambia",
    "emoji": "🇿🇲",
    "rankings": {
      "coffee": 39,
      "population": 64,
      "football": 81,
      "crime_rate": 86,
      "tourism": 96
    }
  },
  {
    "name": "Zimbabwe",
    "emoji": "🇿🇼",
    "rankings": {
      "crime_rate": 32,
      "coffee": 55,
      "population": 73,
      "tourism": 91,
      "gdp": 99
    }
  }
]

// Per-category rank cap (matches packages/core/src/scoring.ts)
export const CATEGORY_CAPS: Record<string, number> = {
  coffee: 73,
  // all others default to 100
}

export const DEFAULT_RANK_CAP = 100
